# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 859fad34f14ec235ac0a045f54436340282617e4e8b1300d7d6a241e78dce355da7735dc54a7f38f50ae6531b586c353abff5bfb6c32e729f98f01cf68791fe7

test:
  secret_key_base: 2e5c03d192551bcdc4a8a55c7de11957d542c488e77770ab22d3a188af708df770bea48076d0d90bb5730ab98e8ff9b8aa3479de057210dd738984ac71d179b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
